"""One-command terminal launcher for TinyAI.

Run:
    python launcher.py

The default training settings are intentionally kept in this source file for
end users. If checkpoints/best.pt is missing, train.py runs automatically,
then the terminal chat starts. The only optional command-line switch is the
device: --cpu or --cuda. Every response is generated by the Transformer.
"""
import argparse
import os
import subprocess
import sys

import torch

from config import get_config
from generate import generate
from model import MiniTransformer
from tokenizer import CharTokenizer

# End-user defaults: no training/configuration command is required.
DEFAULT_CONFIG = "mini"
DEFAULT_EPOCHS = 20
DEFAULT_CHECKPOINT = os.path.join("checkpoints", "best.pt")
DEFAULT_MAX_NEW_TOKENS = 120
DEFAULT_TEMPERATURE = 0.8
DEFAULT_TOP_K = 20
DEFAULT_TOP_P = 0.9


def train_if_needed(checkpoint_path, device):
    """Run the built-in default training pipeline when no checkpoint exists."""
    if os.path.isfile(checkpoint_path):
        return

    print(f"No checkpoint found. Training the default {DEFAULT_CONFIG} model on {device}...")
    command = [
        sys.executable,
        "train.py",
        "--config", DEFAULT_CONFIG,
        "--epochs", str(DEFAULT_EPOCHS),
        "--device", str(device),
        "--out", os.path.dirname(checkpoint_path) or ".",
    ]
    result = subprocess.run(command, check=False)
    if result.returncode != 0 or not os.path.isfile(checkpoint_path):
        raise SystemExit("Training failed or did not create the expected checkpoint.")


def load_model(checkpoint_path, device):
    checkpoint = torch.load(checkpoint_path, map_location=device)
    config = get_config(DEFAULT_CONFIG)
    config.__dict__.update(checkpoint["config"])
    tokenizer = CharTokenizer(checkpoint["tokenizer"])
    model = MiniTransformer(config).to(device)
    model.load_state_dict(checkpoint["model"])
    model.eval()
    return model, tokenizer


def choose_device(args):
    if args.cuda:
        if not torch.cuda.is_available():
            raise SystemExit("CUDA was requested, but no CUDA device is available.")
        return torch.device("cuda")
    return torch.device("cpu") if args.cpu else torch.device("cuda" if torch.cuda.is_available() else "cpu")


def main():
    parser = argparse.ArgumentParser(
        description="Automatically train if needed, then run TinyAI in the terminal."
    )
    device_group = parser.add_mutually_exclusive_group()
    device_group.add_argument("--cpu", action="store_true", help="force CPU training and inference")
    device_group.add_argument("--cuda", action="store_true", help="use CUDA training and inference")
    args = parser.parse_args()

    device = choose_device(args)
    train_if_needed(DEFAULT_CHECKPOINT, device)
    model, tokenizer = load_model(DEFAULT_CHECKPOINT, device)
    print(f"TinyAI ready on {device}. Type !stop to exit.")

    # Conversation memory is serialized as Transformer context, not a response dictionary.
    history = []
    while True:
        try:
            prompt = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye.")
            break

        if prompt == "!stop":
            print("Goodbye.")
            break
        if not prompt:
            continue

        history.append(f"<USER> {prompt} <ASSISTANT>")
        context = " ".join(history)
        answer = generate(
            model,
            tokenizer,
            context,
            device,
            max_new_tokens=DEFAULT_MAX_NEW_TOKENS,
            temperature=DEFAULT_TEMPERATURE,
            top_k=DEFAULT_TOP_K,
            top_p=DEFAULT_TOP_P,
        )
        if answer.startswith(context):
            answer = answer[len(context):]
        answer = answer.strip() or "[The model generated an empty continuation.]"
        print(f"AI: {answer}")
        history.append(answer)


if __name__ == "__main__":
    main()
