"""Command-line launcher for TinyAI.

Run only:
    python launcher.py

If checkpoints/best.pt is missing, the default train.py pipeline runs first.
After training/loading, input() is used continuously until !stop is entered.
Every response is generated by the Transformer; there is no response lookup.
"""
import argparse
import os
import subprocess
import sys

import torch

from config import get_config
from generate import generate
from model import MiniTransformer
from tokenizer import CharTokenizer


def train_if_needed(checkpoint_path, epochs):
    """Run the normal default training pipeline when no checkpoint exists."""
    if os.path.isfile(checkpoint_path):
        return

    print("No checkpoint found. Starting default training before chat...")
    command = [
        sys.executable,
        "train.py",
        "--config",
        "mini",
        "--epochs",
        str(epochs),
        "--out",
        os.path.dirname(checkpoint_path) or ".",
    ]
    result = subprocess.run(command, check=False)
    if result.returncode != 0 or not os.path.isfile(checkpoint_path):
        raise SystemExit("Training failed or did not create the expected checkpoint.")


def load_model(checkpoint_path, device):
    checkpoint = torch.load(checkpoint_path, map_location=device)
    config = get_config("mini")
    config.__dict__.update(checkpoint["config"])
    tokenizer = CharTokenizer(checkpoint["tokenizer"])
    model = MiniTransformer(config).to(device)
    model.load_state_dict(checkpoint["model"])
    model.eval()
    return model, tokenizer


def main():
    parser = argparse.ArgumentParser(description="Train if needed, then run TinyAI in the terminal")
    parser.add_argument("--checkpoint", default="checkpoints/best.pt")
    parser.add_argument("--train-epochs", type=int, default=20)
    parser.add_argument("--device", default="auto", choices=("auto", "cpu", "cuda"))
    parser.add_argument("--max-new-tokens", type=int, default=120)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top-k", type=int, default=20)
    parser.add_argument("--top-p", type=float, default=0.9)
    args = parser.parse_args()

    if args.device == "cuda" and not torch.cuda.is_available():
        raise SystemExit("CUDA was requested but is unavailable. Run with --device cpu.")
    device = torch.device(
        "cuda"
        if args.device == "cuda" or (args.device == "auto" and torch.cuda.is_available())
        else "cpu"
    )

    train_if_needed(args.checkpoint, args.train_epochs)
    model, tokenizer = load_model(args.checkpoint, device)
    print(f"TinyAI ready on {device}. Type !stop to exit.")

    # Keep prior turns as tokenized Transformer context rather than dictionary memory.
    history = []
    while True:
        try:
            prompt = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye.")
            break

        if prompt == "!stop":
            print("Goodbye.")
            break
        if not prompt:
            continue

        history.append(f"<USER> {prompt} <ASSISTANT>")
        context = " ".join(history)
        answer = generate(
            model,
            tokenizer,
            context,
            device,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
            top_k=args.top_k,
            top_p=args.top_p,
        )
        if answer.startswith(context):
            answer = answer[len(context):]
        answer = answer.strip() or "[The model generated an empty continuation.]"
        print(f"AI: {answer}")
        history.append(answer)


if __name__ == "__main__":
    main()
